In [17]:
some = {'rho_trainable': False, 'beta_trainable': False, 'gamma_trainable': False, 'tau_trainable': False}

In [18]:
%time rho_is_onetenth = mle_1g_test.main(**some)

Inferred parameters
    sigmoid lower bound: 0.01    sigmoid upper bound: 0.73    sigmoid midpoint: 0.16    sigmoid rate: 5.22
CPU times: user 5h 45min 3s, sys: 42min 33s, total: 6h 27min 36s
Wall time: 3h 37min 23s


In [19]:
rho_is_ten.save_weights("weights_rho_is_onetenth", save_format="tf")

In [14]:
import mle_1g_test

In [5]:
some = {'rho_trainable': True, 'beta_trainable': True, 'gamma_trainable': False, 'tau_trainable': False}

In [6]:
%time testing_save_model = mle_1g_test.main(**some)

Inferred parameters
    sigmoid lower bound: 0.11    sigmoid upper bound: 0.72    sigmoid midpoint: 0.19    sigmoid rate: 5.76
CPU times: user 5h 37min 23s, sys: 33min 39s, total: 6h 11min 2s
Wall time: 3h 17min 17s


In [7]:
import tensorflow as tf
import psiz

In [29]:
import tensorflow.keras.models

In [31]:
testing_save_model.save("testing_save_model")

In [6]:
testing_save_model.save("saving_whole_model")

In [2]:
models = {}

In [3]:
kinds_of_models = {'rho__beta_trainable': {'rho_trainable': True, 'beta_trainable': True, 'gamma_trainable': False, 'tau_trainable': False},
                   'beta_trainable': {'rho_trainable': False, 'beta_trainable': True, 'gamma_trainable': False, 'tau_trainable': False},
                   'all_trainable': {'rho_trainable': True, 'beta_trainable': True, 'gamma_trainable': True, 'tau_trainable': True},}

In [7]:
import pickle
pickle.dump(kinds_of_models, open("kinds_of_models.p", "wb"))

In [4]:
%%time
for kind_of_model, trainable_kwargs in kinds_of_models.items():
    if kind_of_model not in models:
        models[kind_of_model] = mle_1g_test.main(**trainable_kwargs)
        models[kind_of_model].save_weights("weights_%s" % kind_of_model, save_format="tf")

check
{'rho_trainable': True, 'beta_trainable': True, 'gamma_trainable': False, 'tau_trainable': False}
some
Inferred parameters
    sigmoid lower bound: 0.17    sigmoid upper bound: 0.73    sigmoid midpoint: 0.27    sigmoid rate: 6.74
check
{'rho_trainable': False, 'beta_trainable': True, 'gamma_trainable': False, 'tau_trainable': False}
some
Inferred parameters
    sigmoid lower bound: 0.15    sigmoid upper bound: 0.73    sigmoid midpoint: 0.27    sigmoid rate: 7.32
check
{'rho_trainable': True, 'beta_trainable': True, 'gamma_trainable': True, 'tau_trainable': True}
some
Inferred parameters
    sigmoid lower bound: 0.01    sigmoid upper bound: 0.75    sigmoid midpoint: 0.50    sigmoid rate: 3.71
CPU times: user 18h 15min 28s, sys: 2h 17min 23s, total: 20h 32min 52s
Wall time: 11h 4min 30s


In [ ]:
#believe

In [ ]:
models[0]

In [5]:
models

{'rho__beta_trainable': <psiz.models.rate.Rate at 0x7f45a4576670>,
 'beta_trainable': <psiz.models.rate.Rate at 0x7f458c3fe4f0>,
 'all_trainable': <psiz.models.rate.Rate at 0x7f457c5bbd00>}

In [81]:
temp = {
    'name': 'liyah',
    'age': 20,
}
f(**temp)

{'name': 'liyah', 'age': 20}


In [10]:
def f(**kwargs):
    print(kwargs)
    #x = kwargs['rho_trainable']
    #print(x)
for kind, temp in kinds_of_models.items():
    print(temp)
    f(**temp)

{'rho_trainable': True, 'beta_trainable': True, 'gamma_trainable': False, 'tau_trainable': False}
{'rho_trainable': True, 'beta_trainable': True, 'gamma_trainable': False, 'tau_trainable': False}
{'rho_trainable': False, 'beta_trainable': True, 'gamma_trainable': False, 'tau_trainable': False}
{'rho_trainable': False, 'beta_trainable': True, 'gamma_trainable': False, 'tau_trainable': False}
{'rho_trainable': True, 'beta_trainable': True, 'gamma_trainable': True, 'tau_trainable': True}
{'rho_trainable': True, 'beta_trainable': True, 'gamma_trainable': True, 'tau_trainable': True}


In [73]:
a = [1, 2, 3]
b = {'d': 4, 'e': 5}

def f(*args, **kwargs):
    print(args)
    print(kwargs)
    
f(*a, **b)
print("\n")

def f(x, y, z, d=9, e=12):
    print(x, y, z)
    print(d, e)
    
f(*a, **b)
print("\n")

(1, 2, 3)
{'d': 4, 'e': 5}


1 2 3
4 5




In [43]:
# from pathlib import Path
# if not Path("weights_%s" % kind).exists():
#     pass

In [ ]:
model.save_weights("weights_all_trainable", save_format="tf")

In [ ]:
%time models['beta_trainable'] = mle_1g_test.main(rho_trainable=False, beta_trainable=True)

In [31]:
model.weights

[<tf.Variable 'rate_1/stimuli_1/embeddings:0' shape=(25, 2) dtype=float32, numpy=
 array([[-3.3883676e-03,  1.0626771e-02],
        [ 2.9613322e-01,  8.9638844e-02],
        [ 4.4432039e+00, -2.1028849e-01],
        [-1.8982842e+00, -1.3518299e+00],
        [-1.5471303e+00,  1.1815207e-01],
        [-6.8743855e-01, -7.7857548e-01],
        [ 2.6074831e+00, -4.0728876e-01],
        [-2.8688109e+00, -5.2440751e-01],
        [-7.7342927e-01,  1.5208764e+00],
        [-2.9825071e-01, -1.5273470e-01],
        [ 2.1259356e+00, -2.1872059e-01],
        [ 6.0471267e-01,  2.0362294e-01],
        [-2.8474694e-01,  8.8242596e-01],
        [ 4.6799664e+00,  1.7415766e-02],
        [ 3.7174599e+00, -3.0080205e-01],
        [ 4.7393298e+00, -1.8617080e-01],
        [ 4.9100995e+00, -2.9474372e-01],
        [-1.2481384e+00, -1.1335609e+00],
        [ 2.3827784e+00, -7.3949927e-01],
        [-2.3954344e+00, -9.4188076e-01],
        [-1.2319758e+00,  1.6226258e+00],
        [-1.3735065e+00, -1.8783046e

In [28]:
print(model.stimuli.embedding.weights)
#print(type(model.stimuli.embeddings))

[<tf.Variable 'rate_1/stimuli_1/embeddings:0' shape=(25, 2) dtype=float32, numpy=
array([[-3.3883676e-03,  1.0626771e-02],
       [ 2.9613322e-01,  8.9638844e-02],
       [ 4.4432039e+00, -2.1028849e-01],
       [-1.8982842e+00, -1.3518299e+00],
       [-1.5471303e+00,  1.1815207e-01],
       [-6.8743855e-01, -7.7857548e-01],
       [ 2.6074831e+00, -4.0728876e-01],
       [-2.8688109e+00, -5.2440751e-01],
       [-7.7342927e-01,  1.5208764e+00],
       [-2.9825071e-01, -1.5273470e-01],
       [ 2.1259356e+00, -2.1872059e-01],
       [ 6.0471267e-01,  2.0362294e-01],
       [-2.8474694e-01,  8.8242596e-01],
       [ 4.6799664e+00,  1.7415766e-02],
       [ 3.7174599e+00, -3.0080205e-01],
       [ 4.7393298e+00, -1.8617080e-01],
       [ 4.9100995e+00, -2.9474372e-01],
       [-1.2481384e+00, -1.1335609e+00],
       [ 2.3827784e+00, -7.3949927e-01],
       [-2.3954344e+00, -9.4188076e-01],
       [-1.2319758e+00,  1.6226258e+00],
       [-1.3735065e+00, -1.8783046e-01],
       [ 2.61033

In [ ]:
# def f(*a):
#     print(a)
# f(coords)

In [9]:
import pickle 
#start of testing:
with open('DMTS_8odors_5acids_allMice_raw_PerceptualData_forRick_122319.pkl', 'rb') as f:
    data = pickle.load(f)

In [10]:
import pandas as pd
data_values = pd.concat(data["data"])
z = data_values["odor_1st"] == data_values["odor_2nd"]
data_values[z]["response"].mean()

0.7192041857761127

In [35]:
model.stimuli.embeddings.numpy()[0]

array([[-3.3883676e-03,  1.0626771e-02],
       [ 2.9613322e-01,  8.9638844e-02],
       [ 4.4432039e+00, -2.1028849e-01],
       [-1.8982842e+00, -1.3518299e+00],
       [-1.5471303e+00,  1.1815207e-01],
       [-6.8743855e-01, -7.7857548e-01],
       [ 2.6074831e+00, -4.0728876e-01],
       [-2.8688109e+00, -5.2440751e-01],
       [-7.7342927e-01,  1.5208764e+00],
       [-2.9825071e-01, -1.5273470e-01],
       [ 2.1259356e+00, -2.1872059e-01],
       [ 6.0471267e-01,  2.0362294e-01],
       [-2.8474694e-01,  8.8242596e-01],
       [ 4.6799664e+00,  1.7415766e-02],
       [ 3.7174599e+00, -3.0080205e-01],
       [ 4.7393298e+00, -1.8617080e-01],
       [ 4.9100995e+00, -2.9474372e-01],
       [-1.2481384e+00, -1.1335609e+00],
       [ 2.3827784e+00, -7.3949927e-01],
       [-2.3954344e+00, -9.4188076e-01],
       [-1.2319758e+00,  1.6226258e+00],
       [-1.3735065e+00, -1.8783046e-01],
       [ 2.6103315e+00, -1.7003687e-02],
       [-2.1831539e+00,  2.2792988e-01],
       [-1.48570

In [ ]:
coords = model.stimuli.embeddings.numpy()[0]

In [ ]:
#dir(model.stimuli.embeddings)

### Gallery of Plots

In [ ]:
import pickle
with open('DMTS_8odors_5acids_allMice_raw_PerceptualData_forRick_122319.pkl', 'rb') as f:
        data = pickle.load(f)

In [ ]:
import pandas as pd
len(data["data"][0]["odor_1st"].unique())
data_values = pd.concat(data["data"])
len(data_values["odor_2nd"].unique() & data_values["odor_1st"].unique() )

In [ ]:
data["odorNames"]

In [ ]:
import matplotlib.pyplot as plt
def color_plots(mix_one, mix_two, mixture):
    colors = ["black"]*25
    c = data["odorNames"].index(mix_one)
    h = data["odorNames"].index(mix_two)
    ch = data["odorNames"].index(mixture)
    colors[c] = "red"
    colors[h] = "blue"
    colors[ch] = "purple"
    plt.scatter(*coords.T, c = colors)

In [ ]:
color_plots("CinAld", "CPAcd", "CinAld_CPAcd")

In [ ]:
color_plots("CinAld","2Hep","CinAld_2Hep")

In [ ]:
color_plots("CinAld", "IBAcd","CinAld_IBAcd")

In [ ]:
color_plots("CinAld","IVAcd","CinAld_IVAcd")

In [ ]:
color_plots("EB", "CPAcd", "EB_CPAcd")

In [ ]:
color_plots("EB", "2Hep","EB_2Hep")

In [ ]:
color_plots("EB", "IBAcd","EB_IBAcd")

In [ ]:
color_plots("EB","IVAcd","EB_IVAcd")

In [ ]:
color_plots("2MBAcd","CPAcd","2MBAcd_CPAcd")

In [ ]:
color_plots("2MBAcd","2Hep","2MBAcd_2Hep")

In [ ]:
color_plots("2MBAcd","IBAcd", "2MBAcd_IBAcd")

In [ ]:
color_plots("2MBAcd","IVAcd","2MBAcd_IVAcd")

In [ ]:
color_plots("22DMBAcd","CPAcd","22DMBAcd_CPAcd")

In [ ]:
color_plots("22DMBAcd", "2Hep", "22DMBAcd_2Hep")

In [ ]:
color_plots("22DMBAcd", "IBAcd", "22DMBAcd_IBAcd")

In [ ]:
color_plots("22DMBAcd", "IVAcd", "22DMBAcd_IVAcd")

### Histograms

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

In [ ]:
x = np.linspace(-10, 10, 100) 
z = 1/(1 + np.exp(-x)) 
plt.plot(x, z) 

In [ ]:
x = np.linspace(0, 10, 100)
z = np.exp(x)/(1+np.exp(x))
plt.plot(x,z)

In [ ]:
x = np.linspace(0, 1.5, 100)
a = 0.53
b = 5.86
c = 0.72
d = 0.13
z = d + ((c-d)/(1+np.exp(-b*(x-a))))
plt.plot(x,z)

In [ ]:
x = np.linspace(0, 1.5, 100)
z = 0.13+(0.59/(1+np.exp(-5.86*(x-0.53))))
plt.plot(x,z)

In [ ]:
import pickle

In [ ]:
with open('DMTS_8odors_5acids_allMice_raw_PerceptualData_forRick_122319.pkl', 'rb') as f:
        real_data = pickle.load(f)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#np.vstack(real_data["data"])
#real_data["data"][0]
data = pd.concat(real_data["data"])
#data["odor_1st"].unique()
data.loc[:, ["odor_1st", "odor_2nd"]] -= 1

In [ ]:
#pd.concat(real_data["data"])
data.loc[:, ["odor_1st", "odor_2nd"]]

In [ ]:
set_one = data.loc[:, ["odor_1st"]].values
set_two = data.loc[:, ["odor_2nd"]].values
promise = set_one + set_two
promise

In [ ]:
data["odor_1st"].unique()

In [ ]:
dir(data)

In [ ]:
data.odor_1st.array.

In [ ]:
len(real_data["data"])

In [ ]:
#4199 rows = 4199 trials
trial = real_data["data"][1]

In [ ]:
trial.iloc[:,0]

In [ ]:
real_data['odorNames']

In [ ]:
real_data.keys()